environment:
  nodejs_version: "7"

cache:
 - "%LOCALAPPDATA%\\Yarn"

init:
  - git config --global core.autocrlf true

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - yarn --version
  - yarn install

test_script:
  - node_modules\o-tools-livescript\bin\build.cmd
  - node_modules\.bin\mocha --compilers ls:livescript spec\*.ls
  - set EXOSERVICE_TEST_DEPTH=API
  - node_modules\.bin\cucumber-js --tags ~@clionly --tags ~@todo --tags ~@skipWindows --format progress
  - set EXOSERVICE_TEST_DEPTH=CLI
  - node_modules\.bin\cucumber-js --tags ~@apionly --tags ~@todo --tags ~@skipWindows
  - bin\text-run --format robust


# Don't double-build PRs
skip_branch_with_pr: true

build: off
